name: Test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install Trubar
      run: |
        python -m pip install --upgrade pip
        python -m pip install trubar
    - name: Checkout and translate core Orange
      run: |
        git clone https://github.com/biolab/orange3.git
        git clone https://github.com/biolab/orange-widget-base.git
        git clone https://github.com/biolab/orange-canvas-core.git
        trubar translate -s orange-canvas-core/orangecanvas -d trans/orange-canvas-core/orangecanvas --static si/orange-canvas-static si/orange-canvas-core.yaml
        trubar translate -s orange-widget-base/orangewidget -d trans/orange-widget-base/orangewidget si/orange-widget-base.yaml
        trubar translate -s orange3/Orange -d trans/orange3/Orange --static si/orange3-static si/orange3.jaml
        trubar --conf si/test_config.yaml translate -p test_ -s orange3/Orange -d trans/orange3/Orange si/orange3-tests.jaml
    - name: Checkout and translate add-ons
      run: |
        for translation in si/orange3-*.jaml
        do
          name=${translation/si\/orange3-}
          name=${name/.jaml}
          if [[ $name == "tests" ]]
          then
            continue
          fi
          name=${name/.jaml}
          git clone https://github.com/biolab/orange3-$name.git
          trubar translate -s orange3-$name/orangecontrib/$name -d trans/orange3-$name/orangecontrib/$name si/orange3-$name.jaml
        done
